version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: landing-nextjs
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  postgres_data:
